
#include "FEBioReflection.h"
#include "PreciceCallback.h"
#include <rttr/registration>
#include <FECore/FEMaterialPoint.h>
#include <FEBioMech/FEElasticMaterialPoint.h>
#include <FEBioMech/FEActiveFiberStressUC.h>
#include <FEBioMech/FEDamageMaterialPoint.h>
#include <FEBioMech/FEPreStrainElastic.h>
#include <FEBioMech/FETrussMaterial.h>
#include <FEBioMech/FEDonnanEquilibrium.h>
#include <FEBioMech/FEReactiveFatigueMaterialPoint.h>
#include <FEBioMech/FEReactiveVEMaterialPoint.h>
#include <FEBioMech/FEReactiveVEMaterialPoint.h>
#include <FECore/FEDiscreteMaterial.h>
#include <FEBioMech/FEDiscreteElasticMaterial.h>
#include <FEBioMech/FEPlasticFlowCurve.h>
#include <FEBioMech/FEElasticMultigeneration.h>
#include <FEBioMech/FEForceVelocityContraction.h>
#include <FEBioMech/FEViscoElasticMaterial.h>
#include <FEBioMech/FEKinematicGrowth.h>
#include <FEBioMech/FEVonMisesPlasticity.h>
#include <FEBioMech/FEFiberMaterialPoint.h>
#include <FEBioMech/FEConstPrestrain.h>
#include <FEBioMech/FERemodelingElasticMaterial.h>
#include <FEBioMech/FEReactivePlasticDamageMaterialPoint.h>
#include <FEBioMech/FEReactivePlasticityMaterialPoint.h>
#include <FEBioMech/FEMembraneMaterial.h>
#include <FEBioMech/FEDamageTransIsoMooneyRivlin.h>
#include <FEBioMech/FEElasticMixture.h>
#include <FEBioMech/FEMRVonMisesFibers.h>
#include <FEBioRVE/FEElasticMaterial2O.h>
#include <FEBioRVE/FEMicroMaterial.h>
#include <FEBioRVE/FEMicroMaterial2O.h>
#include <FEBioMix/FEBiphasic.h>
#include <FEBioMix/FESolutesMaterialPoint.h>
#include <FEBioMix/FEMultiphasicMultigeneration.h>
#include <FEBioFluid/FEFluidMaterialPoint.h>
#include <FEBioFluid/FEFluidFSI.h>
#include <FEBioFluid/FEBiphasicFSI.h>
#include <FEBioFluid/FEMultiphasicFSI.h>
#include <FEBioFluid/FESolutesMaterial.h>
#include <FEBioFluid/FEThermoFluidMaterialPoint.h>
#include <FEBioFluid/FEFluidSolutes.h>
#include <FEBioFluid/FEPolarFluidMaterialPoint.h>
RTTR_REGISTRATION {
registration::class_<FEMaterialPointArray>("FEMaterialPointArray")
.method("Init", &FEMaterialPointArray::Init)
.method("Serialize", &FEMaterialPointArray::Serialize)
.method("Update", &FEMaterialPointArray::Update)
.method("AddMaterialPoint", &FEMaterialPointArray::AddMaterialPoint)
.method("Components", &FEMaterialPointArray::Components)
.method("GetPointData", &FEMaterialPointArray::GetPointData)
;
registration::class_<FEElasticMaterialPoint>("FEElasticMaterialPoint")
.property("m_buncoupled", &FEElasticMaterialPoint::m_buncoupled)
.property("m_F", &FEElasticMaterialPoint::m_F)
.property("m_J", &FEElasticMaterialPoint::m_J)
.property("m_gradJ", &FEElasticMaterialPoint::m_gradJ)
.property("m_v", &FEElasticMaterialPoint::m_v)
.property("m_a", &FEElasticMaterialPoint::m_a)
.property("m_L", &FEElasticMaterialPoint::m_L)
.property("m_s", &FEElasticMaterialPoint::m_s)
.property("m_p", &FEElasticMaterialPoint::m_p)
.property("m_Wt", &FEElasticMaterialPoint::m_Wt)
.property("m_Wp", &FEElasticMaterialPoint::m_Wp)
.method("Init", &FEElasticMaterialPoint::Init)
.method("Copy", &FEElasticMaterialPoint::Copy)
.method("Serialize", &FEElasticMaterialPoint::Serialize)
.method("Strain", &FEElasticMaterialPoint::Strain)
.method("SmallStrain", &FEElasticMaterialPoint::SmallStrain)
.method("RightCauchyGreen", &FEElasticMaterialPoint::RightCauchyGreen)
.method("LeftCauchyGreen", &FEElasticMaterialPoint::LeftCauchyGreen)
.method("DevRightCauchyGreen", &FEElasticMaterialPoint::DevRightCauchyGreen)
.method("DevLeftCauchyGreen", &FEElasticMaterialPoint::DevLeftCauchyGreen)
.method("RightStretch", &FEElasticMaterialPoint::RightStretch)
.method("LeftStretch", &FEElasticMaterialPoint::LeftStretch)
.method("RightStretchInverse", &FEElasticMaterialPoint::RightStretchInverse)
.method("LeftStretchInverse", &FEElasticMaterialPoint::LeftStretchInverse)
.method("RightHencky", &FEElasticMaterialPoint::RightHencky)
.method("LeftHencky", &FEElasticMaterialPoint::LeftHencky)
.method("Rotation", &FEElasticMaterialPoint::Rotation)
.method("RateOfDeformation", &FEElasticMaterialPoint::RateOfDeformation)
;
registration::class_<FEDamageMaterialPoint>("FEDamageMaterialPoint")
.property("m_Etrial", &FEDamageMaterialPoint::m_Etrial)
.property("m_Emax", &FEDamageMaterialPoint::m_Emax)
.property("m_D", &FEDamageMaterialPoint::m_D)
.method("Copy", &FEDamageMaterialPoint::Copy)
.method("Init", &FEDamageMaterialPoint::Init)
.method("Update", &FEDamageMaterialPoint::Update)
.method("Serialize", &FEDamageMaterialPoint::Serialize)
;
registration::class_<FEPrestrainMaterialPoint>("FEPrestrainMaterialPoint")
.method("Copy", &FEPrestrainMaterialPoint::Copy)
.method("Init", &FEPrestrainMaterialPoint::Init)
.method("Serialize", &FEPrestrainMaterialPoint::Serialize)
.method("initialPrestrain", &FEPrestrainMaterialPoint::initialPrestrain)
.method("setInitialPrestrain", &FEPrestrainMaterialPoint::setInitialPrestrain)
.method("PrestrainCorrection", &FEPrestrainMaterialPoint::PrestrainCorrection)
.method("setPrestrainCorrection", &FEPrestrainMaterialPoint::setPrestrainCorrection)
.method("prestrain", &FEPrestrainMaterialPoint::prestrain)
;
registration::class_<FETrussMaterialPoint>("FETrussMaterialPoint")
.property("m_l", &FETrussMaterialPoint::m_l)
.property("m_tau", &FETrussMaterialPoint::m_tau)
.method("Copy", &FETrussMaterialPoint::Copy)
.method("Serialize", &FETrussMaterialPoint::Serialize)
.method("Init", &FETrussMaterialPoint::Init)
;
registration::class_<FEDonnanEquilibriumMaterialPoint>("FEDonnanEquilibriumMaterialPoint")
.property("m_cFr", &FEDonnanEquilibriumMaterialPoint::m_cFr)
.property("m_cF", &FEDonnanEquilibriumMaterialPoint::m_cF)
.property("m_osm", &FEDonnanEquilibriumMaterialPoint::m_osm)
.property("m_p", &FEDonnanEquilibriumMaterialPoint::m_p)
.property("m_bpi", &FEDonnanEquilibriumMaterialPoint::m_bpi)
.method("Copy", &FEDonnanEquilibriumMaterialPoint::Copy)
.method("Init", &FEDonnanEquilibriumMaterialPoint::Init)
.method("Serialize", &FEDonnanEquilibriumMaterialPoint::Serialize)
;
registration::class_<FEReactiveFatigueMaterialPoint>("FEReactiveFatigueMaterialPoint")
.property("m_wit", &FEReactiveFatigueMaterialPoint::m_wit)
.property("m_wip", &FEReactiveFatigueMaterialPoint::m_wip)
.property("m_Ximax", &FEReactiveFatigueMaterialPoint::m_Ximax)
.property("m_Xitrl", &FEReactiveFatigueMaterialPoint::m_Xitrl)
.property("m_Xip", &FEReactiveFatigueMaterialPoint::m_Xip)
.property("m_aXit", &FEReactiveFatigueMaterialPoint::m_aXit)
.property("m_aXip", &FEReactiveFatigueMaterialPoint::m_aXip)
.property("m_Fit", &FEReactiveFatigueMaterialPoint::m_Fit)
.property("m_Fip", &FEReactiveFatigueMaterialPoint::m_Fip)
.property("m_wbt", &FEReactiveFatigueMaterialPoint::m_wbt)
.property("m_wbp", &FEReactiveFatigueMaterialPoint::m_wbp)
.property("m_wft", &FEReactiveFatigueMaterialPoint::m_wft)
.property("m_fb", &FEReactiveFatigueMaterialPoint::m_fb)
.method("Copy", &FEReactiveFatigueMaterialPoint::Copy)
.method("Init", &FEReactiveFatigueMaterialPoint::Init)
.method("Update", &FEReactiveFatigueMaterialPoint::Update)
.method("Serialize", &FEReactiveFatigueMaterialPoint::Serialize)
;
registration::class_<FEReactiveViscoelasticMaterialPoint>("FEReactiveViscoelasticMaterialPoint")
.method("Copy", &FEReactiveViscoelasticMaterialPoint::Copy)
;
registration::class_<FEReactiveVEMaterialPoint>("FEReactiveVEMaterialPoint")
.property("m_Uv", &FEReactiveVEMaterialPoint::m_Uv)
.property("m_Jv", &FEReactiveVEMaterialPoint::m_Jv)
.property("m_v", &FEReactiveVEMaterialPoint::m_v)
.property("m_f", &FEReactiveVEMaterialPoint::m_f)
.property("m_Et", &FEReactiveVEMaterialPoint::m_Et)
.property("m_Em", &FEReactiveVEMaterialPoint::m_Em)
.property("m_wv", &FEReactiveVEMaterialPoint::m_wv)
.method("Copy", &FEReactiveVEMaterialPoint::Copy)
.method("Init", &FEReactiveVEMaterialPoint::Init)
.method("Update", &FEReactiveVEMaterialPoint::Update)
.method("Serialize", &FEReactiveVEMaterialPoint::Serialize)
;
registration::class_<FEDiscreteMaterialPoint>("FEDiscreteMaterialPoint")
.property("m_dr0", &FEDiscreteMaterialPoint::m_dr0)
.property("m_drp", &FEDiscreteMaterialPoint::m_drp)
.property("m_drt", &FEDiscreteMaterialPoint::m_drt)
.property("m_dvt", &FEDiscreteMaterialPoint::m_dvt)
.method("Copy", &FEDiscreteMaterialPoint::Copy)
.method("Serialize", &FEDiscreteMaterialPoint::Serialize)
;
registration::class_<FEDiscreteElasticMaterialPoint>("FEDiscreteElasticMaterialPoint")
.property("m_Ft", &FEDiscreteElasticMaterialPoint::m_Ft)
.method("Copy", &FEDiscreteElasticMaterialPoint::Copy)
;
registration::class_<FEPlasticFlowCurveMaterialPoint>("FEPlasticFlowCurveMaterialPoint")
.property("m_Ky", &FEPlasticFlowCurveMaterialPoint::m_Ky)
.property("m_w", &FEPlasticFlowCurveMaterialPoint::m_w)
.property("m_binit", &FEPlasticFlowCurveMaterialPoint::m_binit)
.method("Copy", &FEPlasticFlowCurveMaterialPoint::Copy)
.method("Init", &FEPlasticFlowCurveMaterialPoint::Init)
.method("Serialize", &FEPlasticFlowCurveMaterialPoint::Serialize)
;
registration::class_<FEMultigenerationMaterialPoint>("FEMultigenerationMaterialPoint")
.property("m_tgen", &FEMultigenerationMaterialPoint::m_tgen)
.property("m_ngen", &FEMultigenerationMaterialPoint::m_ngen)
.property("m_pmat", &FEMultigenerationMaterialPoint::m_pmat)
.method("Copy", &FEMultigenerationMaterialPoint::Copy)
.method("Serialize", &FEMultigenerationMaterialPoint::Serialize)
.method("Init", &FEMultigenerationMaterialPoint::Init)
.method("Update", &FEMultigenerationMaterialPoint::Update)
;
registration::class_<FEForceVelocityMaterialPoint>("FEForceVelocityMaterialPoint")
.property("m_lambdap", &FEForceVelocityMaterialPoint::m_lambdap)
.property("m_H", &FEForceVelocityMaterialPoint::m_H)
.property("m_Hp", &FEForceVelocityMaterialPoint::m_Hp)
.method("Copy", &FEForceVelocityMaterialPoint::Copy)
.method("Init", &FEForceVelocityMaterialPoint::Init)
.method("Serialize", &FEForceVelocityMaterialPoint::Serialize)
;
registration::class_<FEViscoElasticMaterialPoint>("FEViscoElasticMaterialPoint")
.property("m_Se", &FEViscoElasticMaterialPoint::m_Se)
.property("m_Sep", &FEViscoElasticMaterialPoint::m_Sep)
.property("m_H", &FEViscoElasticMaterialPoint::m_H)
.property("m_Hp", &FEViscoElasticMaterialPoint::m_Hp)
.property("m_alpha", &FEViscoElasticMaterialPoint::m_alpha)
.property("m_alphap", &FEViscoElasticMaterialPoint::m_alphap)
.property("m_sed", &FEViscoElasticMaterialPoint::m_sed)
.property("m_sedp", &FEViscoElasticMaterialPoint::m_sedp)
.method("Copy", &FEViscoElasticMaterialPoint::Copy)
.method("Init", &FEViscoElasticMaterialPoint::Init)
.method("Update", &FEViscoElasticMaterialPoint::Update)
.method("Serialize", &FEViscoElasticMaterialPoint::Serialize)
;
registration::class_<FEKinematicMaterialPoint>("FEKinematicMaterialPoint")
.property("m_Fe", &FEKinematicMaterialPoint::m_Fe)
.property("m_Fg", &FEKinematicMaterialPoint::m_Fg)
.property("m_rhor", &FEKinematicMaterialPoint::m_rhor)
.method("Copy", &FEKinematicMaterialPoint::Copy)
.method("Init", &FEKinematicMaterialPoint::Init)
.method("Update", &FEKinematicMaterialPoint::Update)
.method("Serialize", &FEKinematicMaterialPoint::Serialize)
;
registration::class_<FEJ2PlasticMaterialPoint>("FEJ2PlasticMaterialPoint")
.property("e0", &FEJ2PlasticMaterialPoint::e0)
.property("e1", &FEJ2PlasticMaterialPoint::e1)
.property("sn", &FEJ2PlasticMaterialPoint::sn)
.property("Y0", &FEJ2PlasticMaterialPoint::Y0)
.property("Y1", &FEJ2PlasticMaterialPoint::Y1)
.property("b", &FEJ2PlasticMaterialPoint::b)
.method("Copy", &FEJ2PlasticMaterialPoint::Copy)
.method("Init", &FEJ2PlasticMaterialPoint::Init)
.method("Update", &FEJ2PlasticMaterialPoint::Update)
.method("Serialize", &FEJ2PlasticMaterialPoint::Serialize)
;
registration::class_<FEFiberMaterialPoint>("FEFiberMaterialPoint")
.property("m_Us", &FEFiberMaterialPoint::m_Us)
.property("m_bUs", &FEFiberMaterialPoint::m_bUs)
.method("Copy", &FEFiberMaterialPoint::Copy)
.method("Init", &FEFiberMaterialPoint::Init)
.method("Serialize", &FEFiberMaterialPoint::Serialize)
.method("SetPreStretch", &FEFiberMaterialPoint::SetPreStretch)
.method("ResetPreStretch", &FEFiberMaterialPoint::ResetPreStretch)
.method("FiberPreStretch", &FEFiberMaterialPoint::FiberPreStretch)
;
registration::class_<FERemodelingMaterialPoint>("FERemodelingMaterialPoint")
.property("m_sed", &FERemodelingMaterialPoint::m_sed)
.property("m_dsed", &FERemodelingMaterialPoint::m_dsed)
.property("m_rhor", &FERemodelingMaterialPoint::m_rhor)
.property("m_rhorp", &FERemodelingMaterialPoint::m_rhorp)
.method("Copy", &FERemodelingMaterialPoint::Copy)
.method("Init", &FERemodelingMaterialPoint::Init)
.method("Update", &FERemodelingMaterialPoint::Update)
.method("Serialize", &FERemodelingMaterialPoint::Serialize)
;
registration::class_<FEReactivePlasticDamageMaterialPoint>("FEReactivePlasticDamageMaterialPoint")
.property("m_Fusi", &FEReactivePlasticDamageMaterialPoint::m_Fusi)
.property("m_Fvsi", &FEReactivePlasticDamageMaterialPoint::m_Fvsi)
.property("m_Kv", &FEReactivePlasticDamageMaterialPoint::m_Kv)
.property("m_Ku", &FEReactivePlasticDamageMaterialPoint::m_Ku)
.property("m_gp", &FEReactivePlasticDamageMaterialPoint::m_gp)
.property("m_gpp", &FEReactivePlasticDamageMaterialPoint::m_gpp)
.property("m_gc", &FEReactivePlasticDamageMaterialPoint::m_gc)
.property("m_Fp", &FEReactivePlasticDamageMaterialPoint::m_Fp)
.property("m_Rhat", &FEReactivePlasticDamageMaterialPoint::m_Rhat)
.property("m_wy", &FEReactivePlasticDamageMaterialPoint::m_wy)
.property("m_Eyt", &FEReactivePlasticDamageMaterialPoint::m_Eyt)
.property("m_Eym", &FEReactivePlasticDamageMaterialPoint::m_Eym)
.property("m_di", &FEReactivePlasticDamageMaterialPoint::m_di)
.property("m_dy", &FEReactivePlasticDamageMaterialPoint::m_dy)
.property("m_d", &FEReactivePlasticDamageMaterialPoint::m_d)
.property("m_byld", &FEReactivePlasticDamageMaterialPoint::m_byld)
.property("m_byldt", &FEReactivePlasticDamageMaterialPoint::m_byldt)
.property("m_pMat", &FEReactivePlasticDamageMaterialPoint::m_pMat)
.method("Copy", &FEReactivePlasticDamageMaterialPoint::Copy)
.method("Init", &FEReactivePlasticDamageMaterialPoint::Init)
.method("Update", &FEReactivePlasticDamageMaterialPoint::Update)
.method("Serialize", &FEReactivePlasticDamageMaterialPoint::Serialize)
.method("YieldedBonds", &FEReactivePlasticDamageMaterialPoint::YieldedBonds)
.method("IntactBonds", &FEReactivePlasticDamageMaterialPoint::IntactBonds)
;
registration::class_<FEReactivePlasticityMaterialPoint>("FEReactivePlasticityMaterialPoint")
.property("m_Fusi", &FEReactivePlasticityMaterialPoint::m_Fusi)
.property("m_Fvsi", &FEReactivePlasticityMaterialPoint::m_Fvsi)
.property("m_w", &FEReactivePlasticityMaterialPoint::m_w)
.property("m_Kv", &FEReactivePlasticityMaterialPoint::m_Kv)
.property("m_Ku", &FEReactivePlasticityMaterialPoint::m_Ku)
.property("m_gp", &FEReactivePlasticityMaterialPoint::m_gp)
.property("m_gpp", &FEReactivePlasticityMaterialPoint::m_gpp)
.property("m_gc", &FEReactivePlasticityMaterialPoint::m_gc)
.property("m_byld", &FEReactivePlasticityMaterialPoint::m_byld)
.property("m_Fp", &FEReactivePlasticityMaterialPoint::m_Fp)
.property("m_Rhat", &FEReactivePlasticityMaterialPoint::m_Rhat)
.property("m_pMat", &FEReactivePlasticityMaterialPoint::m_pMat)
.method("Copy", &FEReactivePlasticityMaterialPoint::Copy)
.method("Init", &FEReactivePlasticityMaterialPoint::Init)
.method("Update", &FEReactivePlasticityMaterialPoint::Update)
.method("Serialize", &FEReactivePlasticityMaterialPoint::Serialize)
.method("YieldedBonds", &FEReactivePlasticityMaterialPoint::YieldedBonds)
;
registration::class_<FEMembraneMaterialPoint>("FEMembraneMaterialPoint")
.property("g", &FEMembraneMaterialPoint::g)
.property("s", &FEMembraneMaterialPoint::s)
.method("Copy", &FEMembraneMaterialPoint::Copy)
.method("Serialize", &FEMembraneMaterialPoint::Serialize)
.method("strain", &FEMembraneMaterialPoint::strain)
;
registration::class_<FETIMRDamageMaterialPoint>("FETIMRDamageMaterialPoint")
.property("m_MEtrial", &FETIMRDamageMaterialPoint::m_MEtrial)
.property("m_MEmax", &FETIMRDamageMaterialPoint::m_MEmax)
.property("m_Dm", &FETIMRDamageMaterialPoint::m_Dm)
.property("m_FEtrial", &FETIMRDamageMaterialPoint::m_FEtrial)
.property("m_FEmax", &FETIMRDamageMaterialPoint::m_FEmax)
.property("m_Df", &FETIMRDamageMaterialPoint::m_Df)
.method("Copy", &FETIMRDamageMaterialPoint::Copy)
.method("Init", &FETIMRDamageMaterialPoint::Init)
.method("Update", &FETIMRDamageMaterialPoint::Update)
.method("Serialize", &FETIMRDamageMaterialPoint::Serialize)
;
registration::class_<FEElasticMixtureMaterialPoint>("FEElasticMixtureMaterialPoint")
.property("m_w", &FEElasticMixtureMaterialPoint::m_w)
.method("Copy", &FEElasticMixtureMaterialPoint::Copy)
.method("Init", &FEElasticMixtureMaterialPoint::Init)
.method("Serialize", &FEElasticMixtureMaterialPoint::Serialize)
;
registration::class_<FEMRVonMisesMaterialPoint>("FEMRVonMisesMaterialPoint")
.property("m_kf", &FEMRVonMisesMaterialPoint::m_kf)
.property("m_tp", &FEMRVonMisesMaterialPoint::m_tp)
.method("Copy", &FEMRVonMisesMaterialPoint::Copy)
.method("Serialize", &FEMRVonMisesMaterialPoint::Serialize)
;
registration::class_<FEElasticMaterialPoint2O>("FEElasticMaterialPoint2O")
.property("m_PK1", &FEElasticMaterialPoint2O::m_PK1)
.property("m_G", &FEElasticMaterialPoint2O::m_G)
.property("m_Q", &FEElasticMaterialPoint2O::m_Q)
.method("Copy", &FEElasticMaterialPoint2O::Copy)
.method("Serialize", &FEElasticMaterialPoint2O::Serialize)
;
registration::class_<FEMicroMaterialPoint>("FEMicroMaterialPoint")
.property("m_S", &FEMicroMaterialPoint::m_S)
.property("m_F_prev", &FEMicroMaterialPoint::m_F_prev)
.property("m_macro_energy", &FEMicroMaterialPoint::m_macro_energy)
.property("m_micro_energy", &FEMicroMaterialPoint::m_micro_energy)
.property("m_energy_diff", &FEMicroMaterialPoint::m_energy_diff)
.property("m_macro_energy_inc", &FEMicroMaterialPoint::m_macro_energy_inc)
.property("m_micro_energy_inc", &FEMicroMaterialPoint::m_micro_energy_inc)
.property("m_rve", &FEMicroMaterialPoint::m_rve)
.method("Init", &FEMicroMaterialPoint::Init)
.method("Update", &FEMicroMaterialPoint::Update)
.method("Copy", &FEMicroMaterialPoint::Copy)
.method("Serialize", &FEMicroMaterialPoint::Serialize)
;
registration::class_<FEMicroMaterialPoint2O>("FEMicroMaterialPoint2O")
.property("m_rve", &FEMicroMaterialPoint2O::m_rve)
.property("m_elem_id", &FEMicroMaterialPoint2O::m_elem_id)
.property("m_gpt_id", &FEMicroMaterialPoint2O::m_gpt_id)
.method("Copy", &FEMicroMaterialPoint2O::Copy)
.method("Serialize", &FEMicroMaterialPoint2O::Serialize)
;
registration::class_<FEBiphasicMaterialPoint>("FEBiphasicMaterialPoint")
.property("m_p", &FEBiphasicMaterialPoint::m_p)
.property("m_gradp", &FEBiphasicMaterialPoint::m_gradp)
.property("m_gradpp", &FEBiphasicMaterialPoint::m_gradpp)
.property("m_w", &FEBiphasicMaterialPoint::m_w)
.property("m_pa", &FEBiphasicMaterialPoint::m_pa)
.property("m_phi0", &FEBiphasicMaterialPoint::m_phi0)
.property("m_phi0t", &FEBiphasicMaterialPoint::m_phi0t)
.property("m_phi0p", &FEBiphasicMaterialPoint::m_phi0p)
.property("m_phi0hat", &FEBiphasicMaterialPoint::m_phi0hat)
.property("m_Jp", &FEBiphasicMaterialPoint::m_Jp)
.property("m_ss", &FEBiphasicMaterialPoint::m_ss)
.method("Copy", &FEBiphasicMaterialPoint::Copy)
.method("Serialize", &FEBiphasicMaterialPoint::Serialize)
.method("Init", &FEBiphasicMaterialPoint::Init)
;
registration::class_<FESolutesMaterialPoint>("FESolutesMaterialPoint")
.property("m_nsol", &FESolutesMaterialPoint::m_nsol)
.property("m_c", &FESolutesMaterialPoint::m_c)
.property("m_gradc", &FESolutesMaterialPoint::m_gradc)
.property("m_j", &FESolutesMaterialPoint::m_j)
.property("m_ca", &FESolutesMaterialPoint::m_ca)
.property("m_crp", &FESolutesMaterialPoint::m_crp)
.property("m_psi", &FESolutesMaterialPoint::m_psi)
.property("m_Ie", &FESolutesMaterialPoint::m_Ie)
.property("m_cF", &FESolutesMaterialPoint::m_cF)
.property("m_nsbm", &FESolutesMaterialPoint::m_nsbm)
.property("m_rhor", &FESolutesMaterialPoint::m_rhor)
.property("m_sbmr", &FESolutesMaterialPoint::m_sbmr)
.property("m_sbmrp", &FESolutesMaterialPoint::m_sbmrp)
.property("m_sbmrhat", &FESolutesMaterialPoint::m_sbmrhat)
.property("m_sbmrhatp", &FESolutesMaterialPoint::m_sbmrhatp)
.property("m_sbmrmin", &FESolutesMaterialPoint::m_sbmrmin)
.property("m_sbmrmax", &FESolutesMaterialPoint::m_sbmrmax)
.property("m_k", &FESolutesMaterialPoint::m_k)
.property("m_dkdJ", &FESolutesMaterialPoint::m_dkdJ)
.property("m_dkdJJ", &FESolutesMaterialPoint::m_dkdJJ)
.property("m_dkdc", &FESolutesMaterialPoint::m_dkdc)
.property("m_dkdJc", &FESolutesMaterialPoint::m_dkdJc)
.property("m_dkdcc", &FESolutesMaterialPoint::m_dkdcc)
.property("m_dkdr", &FESolutesMaterialPoint::m_dkdr)
.property("m_dkdJr", &FESolutesMaterialPoint::m_dkdJr)
.property("m_dkdrc", &FESolutesMaterialPoint::m_dkdrc)
.property("m_cri", &FESolutesMaterialPoint::m_cri)
.property("m_crd", &FESolutesMaterialPoint::m_crd)
.property("m_strain", &FESolutesMaterialPoint::m_strain)
.property("m_pe", &FESolutesMaterialPoint::m_pe)
.property("m_pi", &FESolutesMaterialPoint::m_pi)
.property("m_ce", &FESolutesMaterialPoint::m_ce)
.property("m_ci", &FESolutesMaterialPoint::m_ci)
.property("m_ide", &FESolutesMaterialPoint::m_ide)
.property("m_idi", &FESolutesMaterialPoint::m_idi)
.property("m_bsb", &FESolutesMaterialPoint::m_bsb)
.method("Copy", &FESolutesMaterialPoint::Copy)
.method("Serialize", &FESolutesMaterialPoint::Serialize)
.method("Init", &FESolutesMaterialPoint::Init)
.method("Osmolarity", &FESolutesMaterialPoint::Osmolarity)
;
registration::class_<FEMultigenSBMMaterialPoint>("FEMultigenSBMMaterialPoint")
.property("m_ngen", &FEMultigenSBMMaterialPoint::m_ngen)
.property("m_Fi", &FEMultigenSBMMaterialPoint::m_Fi)
.property("m_Ji", &FEMultigenSBMMaterialPoint::m_Ji)
.property("m_nsbm", &FEMultigenSBMMaterialPoint::m_nsbm)
.property("m_gsbmr", &FEMultigenSBMMaterialPoint::m_gsbmr)
.property("m_gsbmrp", &FEMultigenSBMMaterialPoint::m_gsbmrp)
.property("m_lsbmr", &FEMultigenSBMMaterialPoint::m_lsbmr)
.property("m_tgen", &FEMultigenSBMMaterialPoint::m_tgen)
.method("Copy", &FEMultigenSBMMaterialPoint::Copy)
.method("Serialize", &FEMultigenSBMMaterialPoint::Serialize)
.method("Init", &FEMultigenSBMMaterialPoint::Init)
.method("Update", &FEMultigenSBMMaterialPoint::Update)
;
registration::class_<FEFluidMaterialPoint>("FEFluidMaterialPoint")
.property("m_r0", &FEFluidMaterialPoint::m_r0)
.property("m_vft", &FEFluidMaterialPoint::m_vft)
.property("m_aft", &FEFluidMaterialPoint::m_aft)
.property("m_Lf", &FEFluidMaterialPoint::m_Lf)
.property("m_ef", &FEFluidMaterialPoint::m_ef)
.property("m_efdot", &FEFluidMaterialPoint::m_efdot)
.property("m_gradef", &FEFluidMaterialPoint::m_gradef)
.property("m_pf", &FEFluidMaterialPoint::m_pf)
.property("m_sf", &FEFluidMaterialPoint::m_sf)
.method("Copy", &FEFluidMaterialPoint::Copy)
.method("Serialize", &FEFluidMaterialPoint::Serialize)
.method("Init", &FEFluidMaterialPoint::Init)
.method("RateOfDeformation", &FEFluidMaterialPoint::RateOfDeformation)
.method("Spin", &FEFluidMaterialPoint::Spin)
.method("Vorticity", &FEFluidMaterialPoint::Vorticity)
;
registration::class_<FEFSIMaterialPoint>("FEFSIMaterialPoint")
.property("m_w", &FEFSIMaterialPoint::m_w)
.property("m_aw", &FEFSIMaterialPoint::m_aw)
.property("m_Jdot", &FEFSIMaterialPoint::m_Jdot)
.property("m_ss", &FEFSIMaterialPoint::m_ss)
.method("Copy", &FEFSIMaterialPoint::Copy)
.method("Serialize", &FEFSIMaterialPoint::Serialize)
.method("Init", &FEFSIMaterialPoint::Init)
;
registration::class_<FEBiphasicFSIMaterialPoint>("FEBiphasicFSIMaterialPoint")
.property("m_Lw", &FEBiphasicFSIMaterialPoint::m_Lw)
.property("m_gradJ", &FEBiphasicFSIMaterialPoint::m_gradJ)
.property("m_phi0", &FEBiphasicFSIMaterialPoint::m_phi0)
.property("m_ss", &FEBiphasicFSIMaterialPoint::m_ss)
.method("Copy", &FEBiphasicFSIMaterialPoint::Copy)
.method("Serialize", &FEBiphasicFSIMaterialPoint::Serialize)
.method("Init", &FEBiphasicFSIMaterialPoint::Init)
;
registration::class_<FEMultiphasicFSIMaterialPoint>("FEMultiphasicFSIMaterialPoint")
.property("m_nsol", &FEMultiphasicFSIMaterialPoint::m_nsol)
.property("m_c", &FEMultiphasicFSIMaterialPoint::m_c)
.property("m_ca", &FEMultiphasicFSIMaterialPoint::m_ca)
.property("m_gradc", &FEMultiphasicFSIMaterialPoint::m_gradc)
.property("m_j", &FEMultiphasicFSIMaterialPoint::m_j)
.property("m_cdot", &FEMultiphasicFSIMaterialPoint::m_cdot)
.property("m_psi", &FEMultiphasicFSIMaterialPoint::m_psi)
.property("m_Ie", &FEMultiphasicFSIMaterialPoint::m_Ie)
.property("m_pe", &FEMultiphasicFSIMaterialPoint::m_pe)
.property("m_cF", &FEMultiphasicFSIMaterialPoint::m_cF)
.property("m_k", &FEMultiphasicFSIMaterialPoint::m_k)
.property("m_dkdJ", &FEMultiphasicFSIMaterialPoint::m_dkdJ)
.property("m_dkdJJ", &FEMultiphasicFSIMaterialPoint::m_dkdJJ)
.property("m_dkdc", &FEMultiphasicFSIMaterialPoint::m_dkdc)
.property("m_dkdJc", &FEMultiphasicFSIMaterialPoint::m_dkdJc)
.property("m_dkdcc", &FEMultiphasicFSIMaterialPoint::m_dkdcc)
.method("Copy", &FEMultiphasicFSIMaterialPoint::Copy)
.method("Serialize", &FEMultiphasicFSIMaterialPoint::Serialize)
.method("Init", &FEMultiphasicFSIMaterialPoint::Init)
.method("Osmolarity", &FEMultiphasicFSIMaterialPoint::Osmolarity)
;
registration::class_<FEThermoFluidMaterialPoint>("FEThermoFluidMaterialPoint")
.property("m_T", &FEThermoFluidMaterialPoint::m_T)
.property("m_Tdot", &FEThermoFluidMaterialPoint::m_Tdot)
.property("m_gradT", &FEThermoFluidMaterialPoint::m_gradT)
.property("m_k", &FEThermoFluidMaterialPoint::m_k)
.property("m_K", &FEThermoFluidMaterialPoint::m_K)
.property("m_dKJ", &FEThermoFluidMaterialPoint::m_dKJ)
.property("m_dKT", &FEThermoFluidMaterialPoint::m_dKT)
.property("m_cv", &FEThermoFluidMaterialPoint::m_cv)
.property("m_dcvJ", &FEThermoFluidMaterialPoint::m_dcvJ)
.property("m_dcvT", &FEThermoFluidMaterialPoint::m_dcvT)
.property("m_cp", &FEThermoFluidMaterialPoint::m_cp)
.property("m_q", &FEThermoFluidMaterialPoint::m_q)
.method("Copy", &FEThermoFluidMaterialPoint::Copy)
.method("Serialize", &FEThermoFluidMaterialPoint::Serialize)
.method("Init", &FEThermoFluidMaterialPoint::Init)
;
registration::class_<FEFluidSolutesMaterialPoint>("FEFluidSolutesMaterialPoint")
.property("m_nsol", &FEFluidSolutesMaterialPoint::m_nsol)
.property("m_c", &FEFluidSolutesMaterialPoint::m_c)
.property("m_ca", &FEFluidSolutesMaterialPoint::m_ca)
.property("m_gradc", &FEFluidSolutesMaterialPoint::m_gradc)
.property("m_j", &FEFluidSolutesMaterialPoint::m_j)
.property("m_cdot", &FEFluidSolutesMaterialPoint::m_cdot)
.property("m_psi", &FEFluidSolutesMaterialPoint::m_psi)
.property("m_Ie", &FEFluidSolutesMaterialPoint::m_Ie)
.property("m_pe", &FEFluidSolutesMaterialPoint::m_pe)
.property("m_k", &FEFluidSolutesMaterialPoint::m_k)
.property("m_dkdJ", &FEFluidSolutesMaterialPoint::m_dkdJ)
.property("m_dkdJJ", &FEFluidSolutesMaterialPoint::m_dkdJJ)
.property("m_dkdc", &FEFluidSolutesMaterialPoint::m_dkdc)
.property("m_dkdJc", &FEFluidSolutesMaterialPoint::m_dkdJc)
.property("m_dkdcc", &FEFluidSolutesMaterialPoint::m_dkdcc)
.method("Copy", &FEFluidSolutesMaterialPoint::Copy)
.method("Serialize", &FEFluidSolutesMaterialPoint::Serialize)
.method("Init", &FEFluidSolutesMaterialPoint::Init)
.method("Osmolarity", &FEFluidSolutesMaterialPoint::Osmolarity)
;
registration::class_<FEPolarFluidMaterialPoint>("FEPolarFluidMaterialPoint")
.property("m_gf", &FEPolarFluidMaterialPoint::m_gf)
.property("m_gfdot", &FEPolarFluidMaterialPoint::m_gfdot)
.property("m_hf", &FEPolarFluidMaterialPoint::m_hf)
.property("m_sfa", &FEPolarFluidMaterialPoint::m_sfa)
.property("m_Psi", &FEPolarFluidMaterialPoint::m_Psi)
.method("Copy", &FEPolarFluidMaterialPoint::Copy)
.method("Serialize", &FEPolarFluidMaterialPoint::Serialize)
.method("Init", &FEPolarFluidMaterialPoint::Init)
.method("RelativeSpin", &FEPolarFluidMaterialPoint::RelativeSpin)
;
}
